---

name: Run unit tests/linters

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        androidGradlePluginVersion: ["4.0.2", "4.1.0-rc03", "4.1.0-alpha08", "4.2.0-alpha13"]
    steps:
      - uses: actions/checkout@v2
      - name: Run gradle check
        run: ./gradlew check
        env:
          ANDROID_GRADLE_PLUGIN_VERSION: ${{ matrix.androidGradlePluginVersion }}
